name: Update README

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "0 */1 * * *"

jobs:
    markscribe:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

            - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
              with:
                  go-version: "stable"

            - name: Install markscribe
              run: go install github.com/muesli/markscribe@master

            - name: Run markscribe
              run: "$(go env GOPATH)/bin/markscribe -write README.md templates/README.md.tpl"
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

            - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  commit_message: Update generated README
                  branch: main
                  commit_user_name: readme-scribe 🤖
                  commit_user_email: actions@github.com
                  commit_author: readme-scribe 🤖 <actions@github.com>
